- address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' # WETH
  logoUrl: 'https://assets.coingecko.com/coins/images/2518/thumb/weth.png'
- address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' # USDC
  logoUrl: 'https://assets.coingecko.com/coins/images/6319/thumb/USD_Coin_icon.png'
- address: '0xdAC17F958D2ee523a2206206994597C13D831ec7' # USDT
  logoUrl: 'https://assets.coingecko.com/coins/images/325/thumb/Tether.png'
- address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' # WBTC
  logoUrl: 'https://assets.coingecko.com/coins/images/7598/thumb/wrapped_bitcoin_wbtc.png'
